 export const ActionTypes = {
   ADD_ITEM: "ADD_ITEM",
   DELETE_ITEM: "DELETE_ITEM",
   VIEW_ITEMS: "VIEW_ITEMS",
   DELETE_ITEMS: "DELETE_ITEMS",
   VIEW_ITEM: "VIEW_ITEM",
   SEARCH_ITEMS: "SEARCH_ITEMS",
   FILTER_ITEMS: "FILTER_ITEMS",
   UPDATE_ITEM: "UPDATE_ITEM"
 };
  
  export default ActionTypes;