# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  client-tests:
    name: Running Client Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing Client Dependencies
      run: cd client && npm install
    - name: Client Tests
      run: cd client && npm run test
      
  server-test:
    name: Running Server Tests
    runs-on: ubuntu-latest
    env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing Server Dependencies
      run: cd server && npm install
    - name: Server Tests
      run: cd server && npm run test
      
